## Вычисления с помощью Numpy

### Задание 1

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [4]:
a1 = a[0:, 0]
a1

array([1, 2, 3, 3, 1])

In [5]:
b1 = np.mean(a1)
b1

2.0

In [6]:
a2 = a[0:, 1]
a2

array([ 6,  8, 11, 10,  7])

In [7]:
b2 = np.mean(a2)
b2

8.4

In [8]:
mean_a = np.array([b1, b2])
mean_a

array([2. , 8.4])

### Задание 2

In [9]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [10]:
r1 = a_centered[0:, 0]
r1

array([-1.,  0.,  1.,  1., -1.])

In [11]:
r2 = a_centered[0:, 1]
r2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [12]:
a_centered_sp = r1 @ r2
a_centered_sp

8.0

In [13]:
N = (a_centered.shape[0])
t = a_centered_sp / (N-1)
t

2.0

## Работа с данными в Pandas

### Задание 1

In [14]:
import pandas as pd

In [15]:
authors = pd.DataFrame({
    "author_id": [1, 2, 3],
    "author_name": ["Тугенев", "Чехов", "Островский"]
})

authors


author_id author_name
0          1     Тугенев
1          2       Чехов
2          3  Островский

In [16]:
books = pd.DataFrame({
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price": [450, 300, 350, 500, 450, 370, 290]
})

books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2

In [17]:
authors_price = pd.merge(authors, books, on='author_id', how='outer')
authors_price

author_id author_name            book_title  price
0          1     Тугенев           Отцы и дети    450
1          1     Тугенев                 Рудин    300
2          1     Тугенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3

In [18]:
top5 = authors_price.nlargest(5, "price")
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1     Тугенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1     Тугенев  Дворянское гнездо    350

### Задание 4

In [19]:
authors_stat = authors_price.groupby("author_name")
authors_stat["price"].agg({'min', 'max', 'mean'})



min        mean  max
author_name                      
Островский   290  330.000000  370
Тугенев      300  366.666667  450
Чехов        450  475.000000  500

In [20]:
authors_price.describe()

author_id       price
count   7.000000    7.000000
mean    1.857143  387.142857
std     0.899735   80.976187
min     1.000000  290.000000
25%     1.000000  325.000000
50%     2.000000  370.000000
75%     2.500000  450.000000
max     3.000000  500.000000

In [32]:
k = np.array([1,10,2])
np.median(k)

2.0

In [34]:
authors_price.corr()

author_id     price
author_id   1.000000 -0.120915
price      -0.120915  1.000000

In [43]:
authors_price.to_csv(DZ_nub_1, encoding='utf-8')

NameError: name 'DZ_nub_1' is not defined